services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - /home/dmitry/.elasticsearch/data/:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - /home/dmitry/.ollama/:/root/.ollama/
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  magic:
    image: mageai/mageai:latest
    command: mage start linux-support-bot
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/dmitry/Documents/Programming/Python/llm-zoomcamp/
      ENV: /home/dmitry/Documents/Programming/Python/llm-zoomcamp/.env
    ports:
      - 6789:6789
    volumes:
      - .:/home/dmitry/.mage/
    restart: on-failure:5